version: 2.1

jobs:
  init:
    docker:
      - image: cimg/node:14.18.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: "install"
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules
  lint:
    docker:
      - image: cimg/node:14.18.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: "lint"
          command: "npm run lint"
  test:
    docker:
      - image: cimg/node:14.18.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: "lint"
          command: "npm run test"
  build:
    docker:
      - image: cimg/node:14.18.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: "build"
          command: "npm run build"
      - save_cache:
          key: v1-build-{{ .BuildNum }}-branch-{{ .Branch }}
          paths: 
            - dist          

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-suit:
    jobs:
      - init
      - lint:
          requires:
            - init
      - test:
          requires:
            - init
  build:
    jobs:
      - init
      - lint:
          requires:
            - init
      - test:
          requires:
            - init
      - build:
          requires:
            - lint
            - test